### PR TITLE
[RTM] Lowercase the partial as well

### PR DESCRIPTION
**Pull request by richardhj**
Lowercase the partial as well. See #3

### CODE REVIEW

**Comment by discordier** [comment]
Author vallidation is missing.

**Comment by zonky2** [comment]
@richardhj pls update all files and complete like https://github.com/MetaModels/core/issues/1215

or separate PR

**Comment by richardhj** [comment]
Number of build errors reduced.

**Comment by zonky2** [comment]
> .travis.yml - **latest PHP version at first!**

faster :D

**Comment by richardhj** [comment]
Diese Erbsenzählerei 🙄

**Comment by zonky2** [comment]
...ich bin nur der Überbringer der Nachricht - bitte nicht köpfen ;-)

**Comment by discordier** [comment]
Merged, thanks.

**Pull request merged**
